/Users/apprentice/.rvm/rubies/ruby-1.9.3-p194/lib/ruby/site_ruby/1.9.1/rubygems/custom_require.rb:36:in `require': cannot load such file -- restclient (LoadError)
	from /Users/apprentice/.rvm/rubies/ruby-1.9.3-p194/lib/ruby/site_ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
	from /Users/apprentice/Dropbox/craigslist_scraper/lib/email.rb:1:in `<top (required)>'
	from /Users/apprentice/Dropbox/craigslist_scraper/email_init.rb:2:in `require_relative'
	from /Users/apprentice/Dropbox/craigslist_scraper/email_init.rb:2:in `<main>'
/Users/apprentice/.rvm/gems/ruby-1.9.3-p194/gems/sqlite3-1.3.6/lib/sqlite3/database.rb:91:in `initialize': no such table: users (SQLite3::SQLException)
	from /Users/apprentice/.rvm/gems/ruby-1.9.3-p194/gems/sqlite3-1.3.6/lib/sqlite3/database.rb:91:in `new'
	from /Users/apprentice/.rvm/gems/ruby-1.9.3-p194/gems/sqlite3-1.3.6/lib/sqlite3/database.rb:91:in `prepare'
	from /Users/apprentice/.rvm/gems/ruby-1.9.3-p194/gems/sqlite3-1.3.6/lib/sqlite3/database.rb:134:in `execute'
	from /Users/apprentice/Dropbox/craigslist_scraper/lib/user.rb:14:in `load_all_from_db'
	from /Users/apprentice/Dropbox/craigslist_scraper/email_init.rb:5:in `<main>'
/Users/apprentice/.rvm/gems/ruby-1.9.3-p194/gems/sqlite3-1.3.6/lib/sqlite3/database.rb:91:in `initialize': no such table: users (SQLite3::SQLException)
	from /Users/apprentice/.rvm/gems/ruby-1.9.3-p194/gems/sqlite3-1.3.6/lib/sqlite3/database.rb:91:in `new'
	from /Users/apprentice/.rvm/gems/ruby-1.9.3-p194/gems/sqlite3-1.3.6/lib/sqlite3/database.rb:91:in `prepare'
	from /Users/apprentice/.rvm/gems/ruby-1.9.3-p194/gems/sqlite3-1.3.6/lib/sqlite3/database.rb:134:in `execute'
	from /Users/apprentice/Dropbox/craigslist_scraper/lib/user.rb:14:in `load_all_from_db'
	from /Users/apprentice/Dropbox/craigslist_scraper/email_init.rb:5:in `<main>'
/Users/apprentice/.rvm/gems/ruby-1.9.3-p194/gems/sqlite3-1.3.6/lib/sqlite3/database.rb:91:in `initialize': no such table: users (SQLite3::SQLException)
	from /Users/apprentice/.rvm/gems/ruby-1.9.3-p194/gems/sqlite3-1.3.6/lib/sqlite3/database.rb:91:in `new'
	from /Users/apprentice/.rvm/gems/ruby-1.9.3-p194/gems/sqlite3-1.3.6/lib/sqlite3/database.rb:91:in `prepare'
	from /Users/apprentice/.rvm/gems/ruby-1.9.3-p194/gems/sqlite3-1.3.6/lib/sqlite3/database.rb:134:in `execute'
	from /Users/apprentice/Dropbox/craigslist_scraper/lib/user.rb:14:in `load_all_from_db'
	from /Users/apprentice/Dropbox/craigslist_scraper/email_init.rb:5:in `<main>'
/Users/apprentice/.rvm/gems/ruby-1.9.3-p194/gems/sqlite3-1.3.6/lib/sqlite3/database.rb:91:in `initialize': no such table: users (SQLite3::SQLException)
	from /Users/apprentice/.rvm/gems/ruby-1.9.3-p194/gems/sqlite3-1.3.6/lib/sqlite3/database.rb:91:in `new'
	from /Users/apprentice/.rvm/gems/ruby-1.9.3-p194/gems/sqlite3-1.3.6/lib/sqlite3/database.rb:91:in `prepare'
	from /Users/apprentice/.rvm/gems/ruby-1.9.3-p194/gems/sqlite3-1.3.6/lib/sqlite3/database.rb:134:in `execute'
	from /Users/apprentice/Dropbox/craigslist_scraper/lib/user.rb:14:in `load_all_from_db'
	from /Users/apprentice/Dropbox/craigslist_scraper/email_init.rb:7:in `<main>'
/Users/apprentice/.rvm/gems/ruby-1.9.3-p194/gems/sqlite3-1.3.6/lib/sqlite3/database.rb:91:in `initialize': no such table: users (SQLite3::SQLException)
	from /Users/apprentice/.rvm/gems/ruby-1.9.3-p194/gems/sqlite3-1.3.6/lib/sqlite3/database.rb:91:in `new'
	from /Users/apprentice/.rvm/gems/ruby-1.9.3-p194/gems/sqlite3-1.3.6/lib/sqlite3/database.rb:91:in `prepare'
	from /Users/apprentice/.rvm/gems/ruby-1.9.3-p194/gems/sqlite3-1.3.6/lib/sqlite3/database.rb:134:in `execute'
	from /Users/apprentice/Dropbox/craigslist_scraper/lib/user.rb:14:in `load_all_from_db'
	from /Users/apprentice/Dropbox/craigslist_scraper/email_init.rb:7:in `<main>'
/bin/bash: puts: command not found
/Users/apprentice/.rvm/rubies/ruby-1.9.3-p194/bin/ruby: No such file or directory -- email_init.rb (LoadError)
